"""CLAUDE.md M5: credit officer dashboard (approval queue) — Handoff 2 seam
(§10). Approve/reject are compare-and-set (§14) and write an audit entry
(§12); approval additionally creates the Loan + its RepaymentSchedule in the
same transaction, with every monetary value as Decimal/Numeric (§13).

CLAUDE.md §23: the schedule itself (interest split across installments) is
generated by app/loan_calculation.py's dispatcher, selected by the product's
`interest_model` — never hand-rolled here.
"""

from datetime import date, datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import func, update
from sqlmodel import Session, select

from ..audit import write_audit
from ..db import get_session
from ..db_helpers import get_or_404
from ..deps import require_role
from ..loan_calculation import generate_schedule
from ..loan_delinquency import sync_loan_delinquency
from ..time_utils import as_utc
from ..models import (
    ApplicationStatus,
    AuditAction,
    Loan,
    LoanApplication,
    LoanProduct,
    LoanStatus,
    RepaymentSchedule,
    Transaction,
    TransactionType,
    User,
    UserRole,
)
from ..schemas.credit import (
    CollectionsQueueItemResponse,
    CreditApplicationResponse,
    CreditDecisionRequest,
    DisbursementResponse,
    LoanApprovalResponse,
    LoanDefaultRequest,
    LoanResponse,
    PendingDisbursementResponse,
)

router = APIRouter(prefix="/credit", tags=["credit"])


def _row_to_response(
    application: LoanApplication,
    customer: User,
    product: LoanProduct,
    loan_status: LoanStatus | None,
) -> CreditApplicationResponse:
    """Builds the response from already-fetched rows — the shared tail end
    of both `_to_response` (single-item, one extra query for loan_status is
    fine) and the bulk list endpoints below (which join loan_status in
    directly so this never runs per-row in a loop, avoiding the N+1 those
    endpoints used to have)."""
    return CreditApplicationResponse(
        id=application.id,
        customer_full_name=customer.full_name,
        customer_email=customer.email,
        loan_product_name=product.name,
        amount_requested=application.amount_requested,
        status=application.status,
        review_notes=application.review_notes,
        reviewed_at=application.reviewed_at,
        created_at=application.created_at,
        loan_status=loan_status.value if loan_status else None,
    )


def _to_response(
    session: Session, application: LoanApplication, customer: User, product: LoanProduct
) -> CreditApplicationResponse:
    loan_status = session.exec(select(Loan.status).where(Loan.application_id == application.id)).first()
    return _row_to_response(application, customer, product, loan_status)


def create_loan_for_application(
    session: Session, application: LoanApplication, product: LoanProduct
) -> tuple[Loan, date]:
    """Shared by normal approval and the system_administrator override (§8) that
    reactivates a wrongly-rejected application — both must produce an
    identical Loan + RepaymentSchedule, just reached by a different decision
    path. CLAUDE.md §13: Decimal end to end, never float.
    """
    principal = application.amount_requested
    schedule_result = generate_schedule(
        principal=principal,
        rate_percent=product.interest_rate,
        interest_model=product.interest_model,
        term_days=product.repayment_period_days,
        installment_count=product.installment_count,
        start_date=date.today(),
    )
    total_repayable = schedule_result.total_repayable

    loan = Loan(
        application_id=application.id,
        customer_id=application.customer_id,
        loan_product_id=product.id,
        company_id=application.company_id,
        principal=principal,
        interest_rate=product.interest_rate,
        total_repayable=total_repayable,
        outstanding_balance=total_repayable,
        status=LoanStatus.approved,
    )
    session.add(loan)
    session.flush()

    # CLAUDE.md §19 borrower transparency: principal vs interest per
    # installment, not just "amount due".
    for installment in schedule_result.installments:
        session.add(
            RepaymentSchedule(
                loan_id=loan.id,
                company_id=application.company_id,
                installment_number=installment.installment_number,
                due_date=installment.due_date,
                amount_due=installment.amount_due,
                principal_component=installment.principal_component,
                interest_component=installment.interest_component,
            )
        )
    due_date = schedule_result.installments[-1].due_date
    return loan, due_date


def _get_application_bundle(session: Session, application_id: int) -> tuple[LoanApplication, User, LoanProduct]:
    # session.get is tenant-scoped — another company's application_id comes
    # back None here, indistinguishable from "doesn't exist".
    application = session.get(LoanApplication, application_id)
    if application is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Application not found")
    customer = session.get(User, application.customer_id)
    product = session.get(LoanProduct, application.loan_product_id)
    if customer is None or product is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Application not found")
    return application, customer, product


def _credit_application_base_query():
    """One joined query (application + customer + product + loan status)
    instead of 1 + 3N round trips per row — the pattern every list endpoint
    below now shares."""
    return (
        select(LoanApplication, User, LoanProduct, Loan.status)
        .join(User, User.id == LoanApplication.customer_id)
        .join(LoanProduct, LoanProduct.id == LoanApplication.loan_product_id)
        .outerjoin(Loan, Loan.application_id == LoanApplication.id)
    )


@router.get("/queue", response_model=list[CreditApplicationResponse])
def get_credit_queue(
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer)),
) -> list[CreditApplicationResponse]:
    rows = session.exec(
        _credit_application_base_query()
        .where(LoanApplication.status == ApplicationStatus.pending)
        .order_by(LoanApplication.created_at)
    ).all()
    return [_row_to_response(a, c, p, ls) for a, c, p, ls in rows]


@router.get("/applications/{application_id}", response_model=CreditApplicationResponse)
def get_application_detail(
    application_id: int,
    session: Session = Depends(get_session),
    # CLAUDE.md §9: system_administrator may view for oversight; only credit_officer
    # may act (approve/reject below) — same separation-of-duties pattern M3
    # uses for compliance.
    staff: User = Depends(require_role(UserRole.credit_officer, UserRole.system_administrator)),
) -> CreditApplicationResponse:
    sync_loan_delinquency(session)
    application, customer, product = _get_application_bundle(session, application_id)
    return _to_response(session, application, customer, product)


@router.get("/decisions/me", response_model=list[CreditApplicationResponse])
def get_my_recent_decisions(
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer)),
) -> list[CreditApplicationResponse]:
    """CLAUDE.md §9: "own recent decisions" — an M5 requirement alongside the
    approval queue itself."""
    sync_loan_delinquency(session)
    rows = session.exec(
        _credit_application_base_query()
        .where(
            LoanApplication.reviewed_by == officer.id,
            LoanApplication.status != ApplicationStatus.pending,
        )
        .order_by(LoanApplication.reviewed_at.desc())
    ).all()
    return [_row_to_response(a, c, p, ls) for a, c, p, ls in rows]


@router.get("/loans/pending-disbursement", response_model=list[PendingDisbursementResponse])
def get_loans_pending_disbursement(
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer)),
) -> list[PendingDisbursementResponse]:
    rows = session.exec(
        select(Loan, User, LoanProduct)
        .join(User, User.id == Loan.customer_id)
        .join(LoanProduct, LoanProduct.id == Loan.loan_product_id)
        .where(Loan.status == LoanStatus.approved)
        .order_by(Loan.created_at)
    ).all()
    return [
        PendingDisbursementResponse(
            id=loan.id,
            customer_full_name=customer.full_name,
            customer_email=customer.email,
            loan_product_name=product.name,
            principal=loan.principal,
            total_repayable=loan.total_repayable,
            created_at=loan.created_at,
        )
        for loan, customer, product in rows
    ]


@router.post("/applications/{application_id}/approve", response_model=LoanApprovalResponse)
def approve_application(
    application_id: int,
    body: CreditDecisionRequest,
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer)),
) -> LoanApprovalResponse:
    application, customer, product = _get_application_bundle(session, application_id)

    # CLAUDE.md §14: compare-and-set, never a blind UPDATE.
    result = session.execute(
        update(LoanApplication)
        .where(LoanApplication.id == application_id, LoanApplication.status == ApplicationStatus.pending)
        .values(
            status=ApplicationStatus.approved,
            reviewed_by=officer.id,
            reviewed_at=datetime.now(timezone.utc),
            review_notes=body.notes,
        )
    )
    if result.rowcount == 0:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Application is not pending review")

    loan, due_date = create_loan_for_application(session, application, product)

    # CLAUDE.md §19 light exception monitoring: an approval landed within a
    # minute of submission is fast enough to be worth a second look — flagged
    # onto the exceptions list via is_anomaly, not blocked and not rewriting
    # the officer's own notes (advisory, not automation deciding).
    seconds_to_decision = (datetime.now(timezone.utc) - as_utc(application.created_at)).total_seconds()
    is_anomaly = seconds_to_decision < 60

    write_audit(
        session,
        actor=officer,
        action=AuditAction.APPLICATION_APPROVE.value,
        entity_type="LoanApplication",
        entity_id=application_id,
        reason=body.notes,
        company_id=officer.company_id,
        is_anomaly=is_anomaly,
    )
    session.commit()

    application, customer, product = _get_application_bundle(session, application_id)
    session.refresh(loan)
    return LoanApprovalResponse(
        application=_to_response(session, application, customer, product),
        loan=LoanResponse(
            id=loan.id,
            application_id=loan.application_id,
            principal=loan.principal,
            interest_rate=loan.interest_rate,
            total_repayable=loan.total_repayable,
            penalties_accrued=loan.penalties_accrued,
            outstanding_balance=loan.outstanding_balance,
            status=loan.status.value,
        ),
        repayment_due_date=due_date,
        repayment_amount_due=loan.total_repayable,
    )


@router.post("/applications/{application_id}/reject", response_model=CreditApplicationResponse)
def reject_application(
    application_id: int,
    body: CreditDecisionRequest,
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer)),
) -> CreditApplicationResponse:
    _get_application_bundle(session, application_id)  # 404s if not in this company

    result = session.execute(
        update(LoanApplication)
        .where(LoanApplication.id == application_id, LoanApplication.status == ApplicationStatus.pending)
        .values(
            status=ApplicationStatus.rejected,
            reviewed_by=officer.id,
            reviewed_at=datetime.now(timezone.utc),
            review_notes=body.notes,
        )
    )
    if result.rowcount == 0:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Application is not pending review")

    write_audit(
        session,
        actor=officer,
        action=AuditAction.APPLICATION_REJECT.value,
        entity_type="LoanApplication",
        entity_id=application_id,
        reason=body.notes,
        company_id=officer.company_id,
    )
    session.commit()

    application, customer, product = _get_application_bundle(session, application_id)
    return _to_response(session, application, customer, product)


@router.post("/loans/{loan_id}/disburse", response_model=DisbursementResponse)
def disburse_loan(
    loan_id: int,
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer)),
) -> DisbursementResponse:
    """CLAUDE.md M7: simulated disbursement — no real money moves, but it
    still writes a ledger row (rule #9) and is on the suspension block-list,
    not the allow-list (§6: "new applications / disbursements: stopped")."""
    loan = get_or_404(session, Loan, loan_id, detail="Loan not found")

    now = datetime.now(timezone.utc)
    # CLAUDE.md §14: compare-and-set, never a blind UPDATE.
    result = session.execute(
        update(Loan)
        .where(Loan.id == loan_id, Loan.status == LoanStatus.approved)
        .values(status=LoanStatus.active, disbursed_at=now)
    )
    if result.rowcount == 0:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Loan is not awaiting disbursement")

    session.add(
        Transaction(
            loan_id=loan.id,
            customer_id=loan.customer_id,
            company_id=loan.company_id,
            type=TransactionType.disbursement,
            amount=loan.principal,
        )
    )
    write_audit(
        session,
        actor=officer,
        action=AuditAction.LOAN_DISBURSE.value,
        entity_type="Loan",
        entity_id=loan_id,
        company_id=officer.company_id,
    )
    session.commit()

    session.refresh(loan)
    return DisbursementResponse(
        loan=LoanResponse(
            id=loan.id,
            application_id=loan.application_id,
            principal=loan.principal,
            interest_rate=loan.interest_rate,
            total_repayable=loan.total_repayable,
            penalties_accrued=loan.penalties_accrued,
            outstanding_balance=loan.outstanding_balance,
            status=loan.status.value,
            disbursed_at=loan.disbursed_at,
        )
    )


@router.get("/loans/collections", response_model=list[CollectionsQueueItemResponse])
def get_collections_queue(
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer, UserRole.system_administrator)),
) -> list[CollectionsQueueItemResponse]:
    """CLAUDE.md §19: collections/delinquency queue — same pattern as every
    other queue (§10), just filtered on status=overdue instead of pending.

    Two queries total (not 1 + 3N): the loans+customer+product join, then
    one grouped follow-up query for every loan's earliest overdue
    installment, keyed by loan_id. The grouped query is intentionally a
    plain top-level `select(RepaymentSchedule...)` rather than a subquery
    embedded in the first join — CLAUDE.md §5's tenant-scoping listener is
    proven (by the isolation suite) to filter every top-level TenantMixin
    select in a statement; keeping RepaymentSchedule as its own top-level
    query removes any doubt about whether that filter also reaches into a
    nested subquery.
    """
    sync_loan_delinquency(session)

    loan_rows = session.exec(
        select(Loan, User, LoanProduct)
        .join(User, User.id == Loan.customer_id)
        .join(LoanProduct, LoanProduct.id == Loan.loan_product_id)
        .where(Loan.status == LoanStatus.overdue)
        .order_by(Loan.id)
    ).all()

    today = date.today()
    loan_ids = [loan.id for loan, _, _ in loan_rows]
    earliest_overdue_by_loan: dict[int, date] = {}
    if loan_ids:
        earliest_overdue_by_loan = dict(
            session.exec(
                select(RepaymentSchedule.loan_id, func.min(RepaymentSchedule.due_date))
                .where(
                    RepaymentSchedule.loan_id.in_(loan_ids),
                    RepaymentSchedule.is_paid.is_(False),
                    RepaymentSchedule.due_date < today,
                )
                .group_by(RepaymentSchedule.loan_id)
            ).all()
        )

    responses = []
    for loan, customer, product in loan_rows:
        earliest_overdue = earliest_overdue_by_loan.get(loan.id)
        if earliest_overdue is None:
            continue
        responses.append(
            CollectionsQueueItemResponse(
                id=loan.id,
                customer_full_name=customer.full_name,
                customer_email=customer.email,
                loan_product_name=product.name,
                outstanding_balance=loan.outstanding_balance,
                status=loan.status.value,
                earliest_overdue_due_date=earliest_overdue,
                days_overdue=(today - earliest_overdue).days,
            )
        )
    return responses


@router.post("/loans/{loan_id}/mark-defaulted", response_model=LoanResponse)
def mark_loan_defaulted(
    loan_id: int,
    body: LoanDefaultRequest,
    session: Session = Depends(get_session),
    officer: User = Depends(require_role(UserRole.credit_officer, UserRole.system_administrator)),
) -> LoanResponse:
    """CLAUDE.md §1/§19: defaulting a loan is always a human decision, never
    automatic — the system only ever proposes 'overdue', staff decide 'default'."""
    loan = get_or_404(session, Loan, loan_id, detail="Loan not found")

    # CLAUDE.md §14: compare-and-set, never a blind UPDATE.
    result = session.execute(
        update(Loan)
        .where(Loan.id == loan_id, Loan.status == LoanStatus.overdue)
        .values(status=LoanStatus.defaulted)
    )
    if result.rowcount == 0:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Loan is not currently overdue")

    write_audit(
        session,
        actor=officer,
        action=AuditAction.LOAN_MARK_DEFAULTED.value,
        entity_type="Loan",
        entity_id=loan_id,
        reason=body.reason,
        company_id=officer.company_id,
    )
    session.commit()

    session.refresh(loan)
    return LoanResponse(
        id=loan.id,
        application_id=loan.application_id,
        principal=loan.principal,
        interest_rate=loan.interest_rate,
        total_repayable=loan.total_repayable,
        penalties_accrued=loan.penalties_accrued,
        outstanding_balance=loan.outstanding_balance,
        status=loan.status.value,
        disbursed_at=loan.disbursed_at,
    )
