"""M6 transaction table

Revision ID: 013a1af00219
Revises: ed31a40c97f5
Create Date: 2026-09-11 14:31:52.618237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '013a1af00219'
down_revision: Union[str, Sequence[str], None] = 'ed31a40c97f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('disbursement', 'repayment', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_company_id'), 'transaction', ['company_id'], unique=False)
    op.create_index(op.f('ix_transaction_customer_id'), 'transaction', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transaction_loan_id'), 'transaction', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_loan_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_customer_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_company_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
