"""M2: profile table

Revision ID: 36191e87a192
Revises: 7c5bd0f1d119
Create Date: 2026-09-11 05:54:40.706412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36191e87a192'
down_revision: Union[str, Sequence[str], None] = '7c5bd0f1d119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('residential_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_document_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selfie_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'verified', 'rejected', name='kycstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_company_id'), 'profile', ['company_id'], unique=False)
    op.create_index(op.f('ix_profile_kyc_status'), 'profile', ['kyc_status'], unique=False)
    op.create_index(op.f('ix_profile_national_id_number'), 'profile', ['national_id_number'], unique=False)
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_national_id_number'), table_name='profile')
    op.drop_index(op.f('ix_profile_kyc_status'), table_name='profile')
    op.drop_index(op.f('ix_profile_company_id'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
