"""M4: loan product and application tables

Revision ID: 9a5106c74578
Revises: 36191e87a192
Create Date: 2026-09-11 06:33:58.779380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a5106c74578'
down_revision: Union[str, Sequence[str], None] = '36191e87a192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loanproduct',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('repayment_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loanproduct_company_id'), 'loanproduct', ['company_id'], unique=False)
    op.create_table('loanapplication',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('loan_product_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_product_id'], ['loanproduct.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loanapplication_company_id'), 'loanapplication', ['company_id'], unique=False)
    op.create_index(op.f('ix_loanapplication_customer_id'), 'loanapplication', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loanapplication_loan_product_id'), 'loanapplication', ['loan_product_id'], unique=False)
    op.create_index(op.f('ix_loanapplication_status'), 'loanapplication', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loanapplication_status'), table_name='loanapplication')
    op.drop_index(op.f('ix_loanapplication_loan_product_id'), table_name='loanapplication')
    op.drop_index(op.f('ix_loanapplication_customer_id'), table_name='loanapplication')
    op.drop_index(op.f('ix_loanapplication_company_id'), table_name='loanapplication')
    op.drop_table('loanapplication')
    op.drop_index(op.f('ix_loanproduct_company_id'), table_name='loanproduct')
    op.drop_table('loanproduct')
    # ### end Alembic commands ###
