"""M8 audit log anomaly flag

Revision ID: dbcbe450e62a
Revises: 013a1af00219
Create Date: 2026-09-11 18:08:16.218997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbcbe450e62a'
down_revision: Union[str, Sequence[str], None] = '013a1af00219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditlog', sa.Column('is_anomaly', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_auditlog_is_anomaly'), 'auditlog', ['is_anomaly'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditlog_is_anomaly'), table_name='auditlog')
    op.drop_column('auditlog', 'is_anomaly')
    # ### end Alembic commands ###
