"""M5: loan and repayment schedule tables

Revision ID: ed31a40c97f5
Revises: 9a5106c74578
Create Date: 2026-09-11 07:44:22.796422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed31a40c97f5'
down_revision: Union[str, Sequence[str], None] = '9a5106c74578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('loan_product_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_repayable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('approved', 'active', 'repaid', name='loanstatus'), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loanapplication.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_product_id'], ['loanproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_application_id'), 'loan', ['application_id'], unique=True)
    op.create_index(op.f('ix_loan_company_id'), 'loan', ['company_id'], unique=False)
    op.create_index(op.f('ix_loan_customer_id'), 'loan', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loan_loan_product_id'), 'loan', ['loan_product_id'], unique=False)
    op.create_index(op.f('ix_loan_status'), 'loan', ['status'], unique=False)
    op.create_table('repaymentschedule',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repaymentschedule_company_id'), 'repaymentschedule', ['company_id'], unique=False)
    op.create_index(op.f('ix_repaymentschedule_loan_id'), 'repaymentschedule', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repaymentschedule_loan_id'), table_name='repaymentschedule')
    op.drop_index(op.f('ix_repaymentschedule_company_id'), table_name='repaymentschedule')
    op.drop_table('repaymentschedule')
    op.drop_index(op.f('ix_loan_status'), table_name='loan')
    op.drop_index(op.f('ix_loan_loan_product_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_customer_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_company_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_application_id'), table_name='loan')
    op.drop_table('loan')
    # ### end Alembic commands ###
